<h2>{{{ Diseases }}}</h2>
<div>{{{ The Folding@home project (FAH) is dedicated to understanding protein folding, the diseases that result from protein misfolding and aggregation, and novel computational ways to develop new drugs in general. Here, we briefly describe our goals, what we are doing, and some highlights so far. }}}</div>
<div>{{{ A distributed computing project must not only run calculations on millions of PCs, but such projects must produce results, especially in the form of peer-reviewed publications, public lectures, and other ways that disseminate the results from FAH to the greater scientific community. In the sidebar, you will find links to our progress in different areas. }}}</div>
<div>{{{ You will also find updates about our work, advancements and new projects in the main [Folding@home blog](https://foldingathome.org/news/). }}}</div>
<div>{{{ What is protein folding and how is it related to disease? }}}</div>
<div>{{{ Proteins are necklaces of amino acids, long chain molecules. They are the basis of how biology gets things done. As enzymes, they are the driving force behind all of the biochemical reactions that make biology work. As structural elements, they are the main constituent of our bones, muscles, hair, skin and blood vessels. As antibodies, they recognize invading elements and allow the immune system to get rid of the unwanted invaders. For these reasons, scientists have sequenced the human genome - the blueprint for all of the proteins in biology - but how can we understand what these proteins do and how they work? }}}</div>
<div>{{{ However, only knowing this sequence tells us little about what the protein does and how it does it. In order to carry out their function (e.g. as enzymes or antibodies), they must take on a particular shape, also known as a "fold". Thus, proteins are truly amazing machines: before they do their work, they assemble themselves! This self-assembly is called "folding". }}}</div>
<div>{{{ What happens if proteins don't fold correctly? }}}</div>
<div>{{{ Diseases such as Alzheimer's disease, Huntington's disease, cystic fibrosis, BSE (Mad Cow disease), an inherited form of emphysema, and even many cancers are believed to result from protein misfolding. When proteins misfold, they can clump together ("aggregate"). These clumps can often gather in the brain, where they are believed to cause the symptoms of Mad Cow or Alzheimer's disease. }}}</div>
